# Generated by Django 4.2 on 2023-05-03 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adltrack', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_version', models.CharField(max_length=32)),
                ('to_version', models.CharField(max_length=32)),
                ('backported', models.BooleanField()),
                ('commit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='backport_record', to='adltrack.commit')),
            ],
            options={
                'unique_together': {('commit', 'from_version', 'to_version')},
            },
        ),
    ]
