# Generated by Django 4.2 on 2023-05-05 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factory_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='pProcedure',
            new_name='Procedure',
        ),
    ]
