# -*- coding: utf-8 -*-

SCHEMA_NAME = 'portefeuille'

LANGUAGES = ('fr', 'en', 'de', 'es', 'it', 'zh', 'pt')

IGNORE_LEGACY_MO_FOR_LANGUAGES = ('fr',)

FRAME_MAP_MIN_REVISION = 162084

BUNDLE_EXT = 'gnx'

FALLBACK_SCHEMA_VERSIONS = {
    2016: [2009, ]
}

TECHNICAL_TEST_KEY_Y2K = 'y2k'
TECHNICAL_TEST_KEY_CLYPY = 'clypy'
TECHNICAL_TEST_KEY_GRAPHICAL_COHERENCY = 'graphical_coherency'
TECHNICAL_TEST_KEYS = (
    TECHNICAL_TEST_KEY_Y2K,
    TECHNICAL_TEST_KEY_CLYPY,
    TECHNICAL_TEST_KEY_GRAPHICAL_COHERENCY,
)
