# Generated by Django 3.2.19 on 2023-05-09 17:33

import django.core.files.storage
from django.db import migrations, models
import django.utils.timezone
import neoxam.harry.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JsonUntranslated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('comment', models.TextField()),
                ('file', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/data/home/testauto/Myproject/iadev2.0/data/var/harry'), upload_to=neoxam.harry.models.json_upload_to)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Push',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedure_name', models.CharField(max_length=255)),
                ('hostname', models.CharField(max_length=255)),
                ('session_id', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=255)),
                ('file', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/data/home/testauto/Myproject/iadev2.0/data/var/harry'), upload_to=neoxam.harry.models.untranslated_upload_to)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
