# Generated by Django 4.2 on 2023-05-03 16:02

import _socket
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=32, unique=True)),
                ('scm', models.CharField(choices=[('svn', 'Subversion')], default='svn', max_length=16)),
                ('url', models.URLField()),
                ('timeout', models.PositiveIntegerField()),
            ],
            options={
                'unique_together': {('scm', 'url')},
            },
        ),
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(default=_socket.gethostname, max_length=64)),
                ('in_use', models.BooleanField(default=False)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkouts', to='scm.repository')),
            ],
        ),
    ]
