# Generated by Django 4.2 on 2023-05-03 16:02

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.PositiveIntegerField(unique=True)),
                ('path', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('commit_date', models.DateTimeField()),
                ('data', jsonfield.fields.JSONField()),
            ],
            options={
                'get_latest_by': 'revision',
            },
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(choices=[(710, 'gp710'), (2006, 'gp2006'), (2009, 'gp2009')])),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'unique_together': {('version', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ProcedureVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', jsonfield.fields.JSONField()),
                ('head', models.BooleanField(default=True)),
                ('analyzed', models.BooleanField(default=True)),
                ('magnum_compiled', models.BooleanField(default=False)),
                ('commit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedure_versions', to='adltrack.commit')),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedure_versions', to='adltrack.procedure')),
            ],
            options={
                'unique_together': {('procedure', 'commit')},
            },
        ),
    ]
