# Generated by Django 3.2.19 on 2023-05-09 17:33

import django.core.files.storage
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compilation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedure_name', models.CharField(max_length=255)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('compiling', 'Compiling'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('compiled_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('output', models.TextField(blank=True)),
                ('src', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/data/home/testauto/Myproject/iadev2.0/data/var/champagne'), upload_to='%Y/%m', verbose_name='Source')),
                ('patterns', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
