# Generated by Django 4.2 on 2023-05-03 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatchRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('version', models.CharField(max_length=32)),
                ('path', models.CharField(max_length=256)),
                ('status', models.BooleanField()),
                ('ip', models.CharField(max_length=32)),
            ],
        ),
    ]
